### ISSUE TITLE
Notice no index

### ISSUE THREAD

**Issue by bjverde** [terriani/ScoobyPHP#2]
No PHP 7.3, mostrando todos os erros apareceu a mensagem

Notice: Undefined offset: 4 in D:\wamp\www\ScoobyPHP\index.php on line 36

**Comment by bjverde** [comment]
Uma sugestão de solução é incluir um autoload na pasta Library/Helpers incluir um Helper para tratar Arrays para evitar os problemas de Notice. Como além disso o autoload entra na questão das PSR e diminui os includes.

**Comment by terriani** [comment]
> No PHP 7.3, mostrando todos os erros apareceu a mensagem
> 
> Notice: Undefined offset: 4 in D:\wamp\www\ScoobyPHP\index.php on line 36

O notice estava sendo causado por um trecho de código que não estava sendo usado no arquivo index, porém agora já foi retirado.
