### ISSUE TITLE
Trocar new:db para configurar um banco ??

### ISSUE THREAD

**Issue by bjverde** [terriani/ScoobyPHP#4]
Aqui é mais um duvida ? Por que não new:db para configurar um banco ??

execOptionMakeNewDb()
https://github.com/terriani/ScoobyPHP/blob/master/Scooby_CLI.php#L288

a minha ideia é usuário informar todos os parâmetros, assim poderá conectar em um banco existente. 
* HOST
* DATABASE
* USER
* SENHA

Pois o mais provável é usar o banco existente do que criar um

**Comment by terriani** [comment]
O q acha da ideia de deixa o new:db para criar um novo banco e criar uma outra funcionalidade para poder conectar um banco ja existente no framework por exemplo: connect:db ?

**Comment by bjverde** [comment]
> poder conectar um banco ja existente no framework por exemplo: connect:db ?

O que acha de criar de new:db chamar o connect:db e vice e versa. Se alguém tentar criar um banco que já existe no lugar de dar erros simplesmente irá conectar no banco informado. Se informa um banco que não existe via tentar criar.

**Comment by terriani** [comment]
Boa, vou implementar isso agora e refatorar o cli com o helper que você criou, vlw pela ajuda :)
